import test from 'node:test';
import assert from 'node:assert/strict';
import {Kitchen,ACTIONS,DIR,complete} from '../src/engine.js';
import {SCENES,RECIPES,TIMING} from '../src/content.js';
import {FixedPartner} from '../src/partner.js';
const wait=(k,n)=>{for(let i=0;i<n;i++)k.step(['wait','wait']);};
function face(k,id){const st=k.stations.find(s=>s.id===id),p=k.players[0];for(const [dir,[dx,dy]]of Object.entries(DIR))if(k.walkable(st.x-dx,st.y-dy)&&!k.players.some(v=>v.id!==0&&v.x===st.x-dx&&v.y===st.y-dy)){Object.assign(p,{x:st.x-dx,y:st.y-dy,dir,work:null});return st;}throw Error('No approach');}
const act=(k,a)=>k.step([a,'wait']);
function reach(k,p){const seen=new Set([`${p.x},${p.y}`]),q=[[p.x,p.y]];for(let i=0;i<q.length;i++)for(const [dx,dy]of Object.values(DIR)){const x=q[i][0]+dx,y=q[i][1]+dy,key=`${x},${y}`;if(!seen.has(key)&&k.walkable(x,y)){seen.add(key);q.push([x,y]);}}return seen;}
test('fixed roles arise from disconnected floor, flexible scenes and control are connected',()=>{for(const scene of SCENES){const k=new Kitchen({scene:scene.id}),a=reach(k,k.players[0]),b=reach(k,k.players[1]);assert.equal([...a].some(p=>b.has(p)),scene.roleMode==='flexible');if(scene.roleMode==='flexible')assert.deepEqual(a,b);}const k=new Kitchen({scene:'burger-mine',roleMode:'flexible'});assert.deepEqual(reach(k,k.players[0]),reach(k,k.players[1]));});
test('rotation carries an item across partition without moving chefs',()=>{const k=new Kitchen({scene:'burger-mine'}),s=k.stations.find(s=>s.x===7&&s.y===4),positions=k.players.map(p=>[p.x,p.y]);s.item=k.makeFood('beef');s.item.parts[0].stage='cooked';const item=s.item.id;wait(k,180);assert.equal(s.x,5);assert.equal(s.item.id,item);assert.deepEqual(k.players.map(p=>[p.x,p.y]),positions);assert.equal(new Set(k.stations.map(s=>`${s.x},${s.y}`)).size,k.stations.length);});
test('observations omit procedural requirements by default and detach data',()=>{const k=new Kitchen({scene:'burger-mine'}),o=k.observe(0);assert.ok(!('procedures' in o));assert.ok(!JSON.stringify(o).includes('steps'));assert.deepEqual(o.orders[0].ingredients,RECIPES[o.orders[0].recipe].ingredients);o.players[0].x=999;assert.notEqual(k.players[0].x,999);assert.ok(k.observe(0,{procedure:true}).procedures);});
test('primitive action vocabulary cannot manufacture processed ingredients',()=>{const k=new Kitchen();assert.throws(()=>k.step(['give:cooked_beef','wait']));face(k,'fish');act(k,'interact');assert.equal(k.players[0].held.parts[0].stage,'raw');});
test('beef requires chopping, cooking takes time, unfinished heat cannot be picked up',()=>{const k=new Kitchen({scene:'burger-mine'});k.players[0].held=k.makeFood('beef');const pan=face(k,'pan1');act(k,'interact');assert.equal(pan.item,null);const board=face(k,'chop2');act(k,'interact');act(k,'work');wait(k,TIMING.chop-1);assert.equal(board.item.parts[0].stage,'chopped');act(k,'interact');face(k,'pan1');act(k,'interact');assert.ok(pan.cook>0);act(k,'interact');assert.equal(k.players[0].held,null);wait(k,TIMING.cook);act(k,'interact');assert.equal(k.players[0].held.parts[0].stage,'cooked');});
test('movement interrupts chopping',()=>{const k=new Kitchen();const st=face(k,'chop2');st.item=k.makeFood('fish');act(k,'work');act(k,'down');const progress=st.progress;wait(k,20);assert.equal(st.progress,progress);assert.equal(st.item.parts[0].stage,'raw');});
test('assembled pizza must bake before serving and unassembled ingredients cannot enter oven',()=>{const k=new Kitchen({scene:'pizza-castle'});let dish=null;for(const type of RECIPES.pizza.ingredients){const f=k.makeFood(type);f.parts[0].stage='chopped';dish=dish?k.merge(dish,f):f;}k.players[0].held=k.merge(dish,k.makePlate());face(k,'serve');act(k,'interact');assert.equal(k.delivered,0);assert.ok(k.players[0].held);k.players[0].held=k.makeFood('dough');const oven=face(k,'oven1');act(k,'interact');assert.equal(oven.item,null);k.players[0].held=dish;act(k,'interact');wait(k,TIMING.bake);k.players[0].held=k.makePlate();act(k,'interact');assert.ok(k.players[0].held.baked);face(k,'serve');act(k,'interact');assert.equal(k.delivered,1);assert.equal(k.score,80);});
test('burnt food is rejected at serving, including when plated',()=>{const k=new Kitchen({scene:'burger-mine',menu:['burger']});const pan=face(k,'pan1');k.players[0].held=k.makeFood('beef');k.players[0].held.parts[0].stage='chopped';act(k,'interact');wait(k,TIMING.cook+TIMING.burn+1);assert.equal(pan.item.burnt,true);act(k,'interact');const burnt=k.players[0].held;assert.equal(k.merge(burnt,k.makePlate()),null);assert.equal(complete({...burnt,plate:true,parts:RECIPES.burger.parts.map(([type,stage])=>({type,stage}))},RECIPES.burger),false);});
test('used plate returns dirty then can be washed, initial finite stock preserved',()=>{const k=new Kitchen({scene:'burger-mine',menu:['burger']});const plates=face(k,'plates');act(k,'interact');k.players[0].held.parts=RECIPES.burger.parts.map(([type,stage])=>({type,stage}));face(k,'serve');act(k,'interact');assert.equal(plates.plates,3);wait(k,TIMING.return);const ret=face(k,'returns');act(k,'interact');assert.equal(ret.plates,0);assert.equal(k.players[0].held.dirty,true);const sink=face(k,'sink');act(k,'interact');act(k,'work');wait(k,TIMING.wash);assert.equal(sink.item.dirty,false);});
test('collision and direct swap do not overlap agents',()=>{const k=new Kitchen();Object.assign(k.players[0],{x:2,y:2});Object.assign(k.players[1],{x:4,y:2});k.step(['right','left']);assert.equal(k.players[0].x,2);assert.equal(k.players[1].x,4);k.players[1].x=3;k.step(['right','left']);assert.equal(k.players[0].x,2);assert.equal(k.players[1].x,3);});
test('sliding worktops defer when destination is occupied',()=>{const k=new Kitchen({scene:'pizza-castle'});Object.assign(k.players[0],{x:8,y:2});wait(k,80);assert.equal(k.stations.find(s=>s.id==='chop1').x,4);assert.equal(k.players[0].x,8);k.players[0].x=9;wait(k,80);assert.equal(k.stations.find(s=>s.id==='chop1').x,8);});
test('same seed plus joint primitive actions reproduces state and reward, including swapped seats',()=>{const a=new Kitchen({scene:'burger-mine',seed:873,swapSeats:true,horizon:300}),bots=[0,1].map(id=>new FixedPartner(id));for(let t=0;t<300;t++)a.step(bots.map((b,i)=>b.act(a.observe(i))));const ep=a.exportEpisode(),b=new Kitchen(ep);for(const row of ep.trace)b.step(row.actions);assert.deepEqual(a.observe(0),b.observe(0));assert.deepEqual(ep.final,b.exportEpisode().final);assert.equal(a.done,true);const tick=a.tick;a.step(['wait','wait']);assert.equal(a.tick,tick);});
for(const scene of SCENES)test(`${scene.id} scripted smoke produces meals across seeds and seat assignments`,()=>{for(const seed of [1,7,42])for(const swapSeats of [false,true]){const k=new Kitchen({scene:scene.id,seed,swapSeats,horizon:1000}),bots=[0,1].map(id=>new FixedPartner(id));for(let t=0;t<1000;t++)k.step(bots.map((b,i)=>b.act(k.observe(i))));assert.ok(k.delivered>0,`seed ${seed}, swap ${swapSeats}`);assert.equal(new Set(k.players.map(p=>`${p.x},${p.y}`)).size,2);}});
